{% set name = "ovito" %}
{% set version = "3.10.0" %}
{% set sha256 = "abf0f83273da7019cec700daa886f4b07c5be2fa3f3c1aba85c6dfe023a0ae61" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/stuko/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxext-devel') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libXau') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - cmake
    - libboost-headers
    - make  # [unix]
    - sphinx
    - sphinx_rtd_theme
    - qt6-main                              # [build_platform != target_platform]
  host:
    - ffmpeg
    - libnetcdf
    - qt6-main
    - zlib
    - libssh   # [not win]
  run_constrained:
    - menuinst >=1.4.17  # [win]

test:
  commands:
    - command -v ovito  # [unix]
    - where ovito  # [win]
    - if not exist %PREFIX%\\Menu\\ovito.json exit 1  # [win]
    - if not exist %PREFIX%\\Menu\\ovito.ico exit 1  # [win]

about:
  home: https://www.ovito.org
  license: GPL-3.0-or-later
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: Scientific visualization and analysis software for atomistic simulation data
  description: |
    OVITO is a scientific visualization and analysis software for
    atomistic and particle simulation data. It helps scientists gain
    better insights into materials phenomena and physical processes.
    This package provides the OVITO Basic desktop application without the Python modules.
    For all features, use the licensed OVITO Pro version.
    OVITO is being developed by OVITO GmbH, Germany. 
    The developers offer a separate conda package that also includes the OVITO Python module.
  doc_url: https://www.ovito.org/docs/current/
  dev_url: https://gitlab.com/stuko/ovito

extra:
  recipe-maintainers:
    - jan-janssen
    - ericpre
    - stukowski
