travis:
  secure:
    BINSTAR_TOKEN: VipQYjKPOF4YKXxAs/JJgybS8HPaoEQ3S1SHQHq5ZHQFi9eDTk2Y+lB/dUppC2eMYMvDJUbKgQenYAsaEwjegtIaQZ0tofk+BuYs+W4jRlCO6RGZ0OkaOmocz73aCmpS5mVBnX1G12JRG+ZSgx9EpdIoF7CFoMp1v0J92Nw4b474v7xg9Cr+NeEQMdtEdFuH0wNcqdBLRFdPfGbqQ7L92+RLP+/aBJ6V4pKe49xL/8Ns3wyP/xbsv7Hjf1goPR3LChNXoT+WlDPB0fBiqItwFZdL5pnCVkqMlPOgSfQ2H5f8WjmucWxtvVU4olZbta4g9SdEm30YhkWNH17Kfpo2EK5K0XE0/n6Nm8CuhYzBaxsS7do4nxwRkqa6KaQw3m/2lG1egWdZE7Q+sd168LO2K+kAjI/m0djYewFTaJdW2TMPlZdzUzhZjnrXeqBMHQgcEgcpqUF9+jdTEBVFTWk/FMHbFy1Og2bG3DmgS2o8cW/p68J+ya4ae6iMu1pnpf/rgMCnpn0AnHcGQlwKaRJ0THIqfCQ++zhBzugAraBIReLYrYrxkvxXy11VXK2OmfKPYZ6vEKOV/yzHz+0KcKhSO9y+6gf18SrsdV8kJangq7C2/lvM447XKiJjcx3zr1LbTng1ekR5H8uUpd4rpJddkTfLg/h3+dXZRjQS8w5nBMw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
